name: Automation
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0,12 * * *' 

      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install python dependencies if any

    - name: stash old events file
      run: cp sup.txt sup.old.txt

    - name: Run the scripts 1
      run: python ./gigs/inertia-entertainment.py | tee sup.txt
    - name: Run the scripts 2    
      run: python ./matches/bokke-schedule.py | tee -a sup.txt
    - name: Run the scripts 3      
      run: python ./matches/proteas-schedule.py | tee -a sup.txt
    - name: Run the scripts 4      
      run: python ./matches/spurs-schedule.py | tee -a sup.txt

    - name: Commit and push if changes
      run: |
        if ! diff -q sup.txt sup.old.txt ; then
        git config --local user.email "grmtek_bot@github.com"
        git config --local user.name "grmtek Action"
        git add 'sup.txt'
        git commit -m "Changes noticed at $(date +"%m-%d-%Y %T")" 
        git push
        else echo "No new events to report"
        fi
