name: Automation
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0,12 * * *' 

      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install python dependencies if any

    - name: Run the scripts 1
      run: python ./gigs/inertia-entertainment.py
    - name: Run the scripts 2    
      run: python ./matches/bokke-schedule.py
    - name: Run the scripts 3      
      run: python ./matches/proteas-schedule.py
    - name: Run the scripts 4      
      run: python ./matches/spurs-schedule.py

    - name: Check for changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.1 # This action checks if there are any changes
      with:
        paths: 'sup.txt' 

    - name: Commit and push if changes
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "grmtek_bot@github.com"
        git config --local user.name "grmtek Action"
        git commit -am "Changes noticed at $(date +"%m-%d-%Y %T")" 
        git push
